version: 1.0.{build}
image: Visual Studio 2017
matrix:
  fast_finish: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))



before_build:
- ps: nuget restore -Verbosity quiet
- ps: choco install opencover.portable --no-progress -y
- ps: choco install codecov --no-progress -y
build:
  verbosity: minimal



test_script:
- ps: OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:".\QDatas.UnitTest\bin\Debug\netcoreapp2.1\QDatas.UnitTest.dll" -filter:"+[QDatas*]* -[QDatas.UnitTest]*" -output:".\QData_coverage.xml" -oldstyle
- ps: codecov -f ".\QData_coverage.xml"



artifacts:
- path: '.\QDatas.Core\bin\Debug\QData.*.nupkg'



deploy:
- provider: NuGet
  api_key:
    secure: OXY8QfF92dsRyE6eiaFMzaYI6YvA/NUsoI+lOPsE2gSB7LGIlvfiHg1Tt0HOTdwU
  on:
    APPVEYOR_REPO_TAG: true